module.exports = {
	googleClientID: process.env.GOOGLE_CLIENT_ID,
	googleClientSecret: process.env.GOOGLE_CLIENT_SECRET,
	FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
	FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
	MONGO_URI: process.env.MONGO_URI,
	COOKIE_KEY: process.env.COOKIE_KEY,
	STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
	STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
	SENDGRID_KEY: process.env.SENDGRID_KEY,
	REDIRECT_DOMAIN: process.env.REDIRECT_DOMAIN
};
