export const FETCH_USER = 'FETCH_USER';
export const FETCH_SURVEYS = 'FETCH_SURVEYS';
export const DELETE_SURVEY = 'DELETE_SURVEY';
export const SERVER_ERROR = 'SERVER_ERROR';
export const SELECTED_SURVEY_ID = 'SELECTED_SURVEY_ID';
